version: '3.7'
services:
  minio1:
    image: minio/minio
    ports:
      - 9001:9000
    environment:
      MINIO_ROOT_USER: hello11111
      MINIO_ROOT_PASSWORD: hello11111
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio1:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m
    volumes:
      - ./var/minio:/data
