version: '3.7'
services:
  minio1:
    image: minio/minio
    ports:
      - 9001:9000
    environment:
      MINIO_ROOT_USER: hello11111
      MINIO_ROOT_PASSWORD: hello11111
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio1:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m
    volumes:
      - ./var/minio:/data
  imaginary:
    image: h2non/imaginary
    network_mode: host
    environment:
      PORT: 9002
    # XXX `-http-cache-ttl 0` will tell imaginary to always return `Cache-Control: private, no-cache, no-store, must-revalidate`.
    #     There should be a line in nginx proxy config to override this header in case of a sucesful response:
    #     /etc/nginx/sites-available/com.xxx.imaginary
    #     add_header Cache-Control 'public, s-maxage=31556926, max-age=31556926, no-transform';
    # This trick is necessary because imaginary will always return the same
    # value for Cache-Control header. Even if was unable to fetch original image
    # it will return the same Cache-Control header.
    command: -enable-url-source -http-read-timeout 10 -http-cache-ttl 0
    restart: always
